steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}',
    '-f', '.github/build_and_publish/Dockerfile',
    '.'
  ]

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}'
  ]

# Deploy to Cloud Run jobs
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'beta', 'run', 'jobs', 'update', '${_JOB_NAME}',
    '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG}',
    '--region', '${_REGION}',
    '--cpu', '${_CPU}',
    '--memory', '${_MEMORY}',
    '--tasks', '1',
    '--max-retries', '3',
    '--set-env-vars', 'FOO=bar',  # Add your environment variables here
    '--service-account', '${_SERVICE_ACCOUNT}'
  ]

# If the job doesn't exist, create it
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if ! gcloud beta run jobs describe ${_JOB_NAME} --region ${_REGION} > /dev/null 2>&1; then
        gcloud beta run jobs create ${_JOB_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:${_TAG} \
          --region ${_REGION} \
          --cpu ${_CPU} \
          --memory ${_MEMORY} \
          --tasks 1 \
          --max-retries 3 \
          --set-env-vars FOO=bar \
          --service-account ${_SERVICE_ACCOUNT}
      fi

# Optional: Execute the job immediately after deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'beta', 'run', 'jobs', 'execute', '${_JOB_NAME}',
    '--region', '${_REGION}'
  ]

substitutions:
  _REGION: 'us-central1'  # Default region
  _REPOSITORY_NAME: 'policyengine-us-data'  # Your Artifact Registry repository name
  _IMAGE_NAME: 'build-and-publish'  # Your image name
  _TAG: 'latest'  # Image tag
  _JOB_NAME: 'build-and-publish-us-data'  # Cloud Run job name
  _CPU: '1'  # Number of CPUs
  _MEMORY: '2Gi'  # Memory allocation
  _SERVICE_ACCOUNT: 'policyengine-research@policyengine-research.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY