name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy_docs.yaml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GitHub Pages deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install mystmd
          pip install -e .

      - name: Build documentation
        run: make documentation
        env:
          BASE_URL: '/policyengine-us-data'

      - name: Verify documentation build
        run: |
          echo "Checking .nojekyll file exists..."
          test -f docs/_build/html/.nojekyll || (echo "ERROR: .nojekyll file missing!" && exit 1)
          
          echo "Checking index.html exists..."
          test -f docs/_build/html/index.html || (echo "ERROR: index.html missing!" && exit 1)
          
          echo "Checking for correct base URL in HTML..."
          if grep -q 'href="/policyengine-us-data/' docs/_build/html/index.html; then
            echo "✓ Base URL correctly set in HTML"
          else
            echo "ERROR: Base URL not found in HTML!" && exit 1
          fi
          
          echo "Documentation build verification passed!"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html
          clean: true