name: Manual tests

on:
  workflow_dispatch:
    inputs:
      test_lite:
        description: 'Run in lite mode'
        required: true
        default: true
        type: boolean

jobs:
  test:
    uses: ./.github/workflows/code_changes.yaml
    with:
      TEST_LITE: ${{ github.event.inputs.test_lite }}
    secrets: inherit
