# Workflow that runs on code changes to a pull request.

name: PR code changes
on:
  pull_request:
    branches:
      - main

    paths:
      - policyengine_us_data/**
      - tests/**
      - .github/workflows/pr_code_changes.yaml  # TEMPORARY
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Check formatting
          uses: "lgeiger/black-action@master"
          with:
              args: ". -l 79 --check"

  MinimalInstallCheck:
    name: Test Minimal Install & Import (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package ONLY (no dev deps)
        run: pip install .
      - name: Test basic import
        run: python -c "import policyengine_us_data; print('Minimal import OK')"
      - name: Test specific failing import
        run: python -c "from policyengine_core.data import Dataset; print('Core import OK')"

  Test:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Install uv
            uses: astral-sh/setup-uv@v5

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.12'
              
          - name: Install package
            run: uv pip install -e .[dev] --system
          - name: Download data inputs
            run: make download
            env:
              HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
              POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
          - name: Build datasets
            run: make data
            env:
              LITE_MODE: true
          - name: Run tests
            run: pytest
          - name: Test documentation builds
            run: make documentation
