name: Changelog entry
on:
  pull_request:
    branches: [main]

jobs:
  require-entry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure changelog entry exists
        run: .github/check-changelog-entry.sh
