name: Changelog entry
on:
  pull_request:
    branches: [main]

jobs:
  require-entry:
    uses: ./.github/workflows/reusable_changelog_check.yaml
    with:
      require_entry: true
      validate_format: true