# Workflow that runs on code changes to a pull request.

name: PR code changes
on:
  pull_request:
    branches:
      - main

    paths:
      - policyengine_us_data/**
      - tests/**

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Check formatting
          uses: "lgeiger/black-action@master"
          with:
              args: ". -l 79 --check"
  Test:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Install uv
            uses: astral-sh/setup-uv@v5
          - uses: "google-github-actions/auth@v2"
            with:
              workload_identity_provider: "projects/322898545428/locations/global/workloadIdentityPools/policyengine-research-id-pool/providers/prod-github-provider"
              service_account: "policyengine-research@policyengine-research.iam.gserviceaccount.com"

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'
              
          - name: Install package
            run: uv pip install -e .[dev] --system
          - name: Test data upload
            run: python test_upload.py
          - name: Download data inputs
            run: make download
            env:
              HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
              POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
          - name: Build datasets
            run: make data
            env:
              TEST_LITE: true
          - name: Run tests
            run: pytest
          - name: Test documentation builds
            run: make documentation