name: Changelog entry
on:
  pull_request:
    branches: [main]

jobs:
  check-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from fork
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "❌ ERROR: This PR is from a fork repository."
            echo "PRs must be created from branches in the main PolicyEngine/policyengine-us-data repository."
            echo "Please close this PR and create a new one following these steps:"
            echo "1. git checkout main"
            echo "2. git pull upstream main"
            echo "3. git checkout -b your-branch-name"
            echo "4. git push -u upstream your-branch-name"
            echo "5. Create PR from the upstream branch"
            exit 1
          fi
          echo "✅ PR is from the correct repository"

  require-entry:
    needs: check-fork
    uses: ./.github/workflows/reusable_changelog_check.yaml
    with:
      require_entry: true
      validate_format: true