"""American Opportunity Credit helpers backed by policyengine-us parameters."""

import math
from functools import lru_cache

import numpy as np


@lru_cache(maxsize=16)
def get_american_opportunity_credit_amount_scale(year: int):
    """Return the policyengine-us AOTC amount scale for a tax year."""
    from policyengine_us import CountryTaxBenefitSystem

    return CountryTaxBenefitSystem().parameters.gov.irs.credits.education.american_opportunity_credit.amount(
        f"{year}-01-01"
    )


def qualifying_expenses_from_american_opportunity_credit(
    credit: float,
    year: int,
) -> float:
    """Return the minimum expenses that generate ``credit`` under PE-US."""
    amount_scale = get_american_opportunity_credit_amount_scale(year)
    return _minimum_base_for_marginal_amount(credit, amount_scale)


def maximum_american_opportunity_credit_per_student(year: int) -> float:
    """Return the maximum AOTC generated by one student under PE-US."""
    amount_scale = get_american_opportunity_credit_amount_scale(year)
    if len(amount_scale.thresholds) == 0:
        return 0.0
    terminal_threshold = max(amount_scale.thresholds)
    return float(amount_scale.calc(np.array([terminal_threshold], dtype=float))[0])


def _minimum_base_for_marginal_amount(amount: float, scale) -> float:
    """Invert a marginal amount schedule using the schedule brackets."""
    amount = max(float(amount), 0)
    if amount == 0:
        return 0.0

    thresholds = np.asarray(scale.thresholds, dtype=float)
    rates = np.asarray(scale.rates, dtype=float)
    if thresholds.size == 0:
        return 0.0

    order = np.argsort(thresholds)
    thresholds = thresholds[order]
    rates = rates[order]

    accrued = 0.0
    for index, (lower, rate) in enumerate(zip(thresholds, rates)):
        lower = float(lower)
        rate = float(rate)
        upper = (
            float(thresholds[index + 1]) if index + 1 < thresholds.size else math.inf
        )

        if amount <= accrued:
            return lower
        if rate <= 0:
            continue
        if math.isinf(upper):
            return lower + (amount - accrued) / rate

        bracket_amount = (upper - lower) * rate
        if amount <= accrued + bracket_amount:
            return lower + (amount - accrued) / rate
        accrued += bracket_amount

    return float(thresholds[-1])
